# блоки без следствия:

prefix : <https://purl.org/agingontology/hasd#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?s ?name ?ageFrom ?ageTo ?system
WHERE {
	?s rdf:type :HASDNode .
	filter not exists {?s :followsTo ?o } .
  ?s :name ?name .
	?s :ageFrom ?ageFrom .
	?s :ageTo ?ageTo .
	?s :system ?system .
 }

# блоки без причины:

prefix : <https://purl.org/agingontology/hasd#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?o ?name ?ageFrom ?ageTo ?system
WHERE {
	?o rdf:type :HASDNode .
	filter not exists {?s :followsTo ?o } .
	?o :name ?name .
	?o :ageFrom ?ageFrom .
	?o :ageTo ?ageTo .
	?o :system ?system .
 }
